spring.application.name=demo-service

# Configuración de Oracle XE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=VERIS_USER
spring.datasource.password=VerisTest2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Estrategia de actualización (None porque ya tenemos los scripts SQL)
spring.jpa.hibernate.ddl-auto=none

# Mostrar SQL formateado en consola (para debuggear como en Node)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# formato fechas
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Guayaquil

# Seguridad - JWT
jwt.secret=${JWT_SECRET:secretKey%veris%2026%proceso%seleccion%desarrollador%senior%fullstack_java}
jwt.expiration=3600000
